### ISSUE TITLE
awkward English phrasing for missing forecast

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#450]
"We could not find NWAC weather forecast"

![image](https://github.com/NWACus/avy/assets/101196/d42cdd8f-a617-4130-8a1f-3af3fc7851ba)

**Comment by floatplane** [comment]
they're both in different spots in the code, right? seems like two issues helps us make sure both get fixed?

**Comment by stevekuznetsov** [comment]
I imagine the underlying cause is identical - regarding where `"the"` is added to the `Outcome` and changed with [this change](https://github.com/NWACus/avy/commit/4bb48c4e40a03b4dd2a4227ead7b9b56cc859f35#diff-ce71dc0436ce489ccbe246c31e4ec535c2e983ceb5ca307d5affbc8b0766ad28L74) but feel free to keep this open and close both if it's true.

**Comment by floatplane** [comment]
fixed in #457
