### ISSUE TITLE
Observation Submission From App Sets the Starting & Creation Date Incorrectly

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#584]
![image](https://github.com/NWACus/avy/assets/119702342/9fcaba74-7704-4e8e-bedb-72d1492545d2)

**Comment by charlotteguard** [comment]
<img width="1397" alt="Screenshot 2023-11-26 at 8 42 54 AM" src="https://github.com/NWACus/avy/assets/119702342/4bd918a8-d635-49f1-829c-15dd2b131290">
<img width="931" alt="Screenshot 2023-11-26 at 8 43 22 AM" src="https://github.com/NWACus/avy/assets/119702342/d1359cfb-c050-405a-bc9b-c6a7f61da0b9">

**Comment by stevekuznetsov** [comment]
It seems like submissions from the app are switching the creation timestamp and the observation timestamp, which is surprising - I don't know that we set the creation time, versus it being auto-set by the POST.

**Comment by floatplane** [comment]
I wonder if we are running into trouble because we don't set `end_date` explicitly, and it's defaulting to the creation date? Or if the website is using `end_date` and we're using `start_date`?

Agreed that creation date is a field that we don't set, and I would expect that to be set by the DB when the new row is written.

**Comment by yuliadub** [comment]
as discussed in the committee call, this could be a UTC related issues where the date is getting set in UTC (if person submits int he afternoon it would be the next day)

**Comment by floatplane** [comment]
grabbing this bug, this is indeed the problem
