### ISSUE TITLE
Logo for SAC is very tiny 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#762]
Look into the logo in the header for obs because it’s tiny 
![Screenshot_20240624-165346_Avy (Preview)~2.jpg](https://github.com/NWACus/avy/assets/119702342/39e8e359-9fac-49ef-be52-27e4dbce199a)

**Comment by stevekuznetsov** [comment]
![File (47)](https://github.com/user-attachments/assets/203218dd-1189-48b7-a3fa-3e18be494faf)

@charlotteguard we can only worry about the height of the logo and let the width increase while keeping aspect ratio, which helps for "short and wide" logos but shifts layout of the header - WDYT? We could offset the title from the left instead of trying to center it, maybe?

**Comment by stevekuznetsov** [comment]
Looks like that's what we do on the Forecast view header.
